INSERT INTO BJ(NAME, NICKNAME) VALUES ('BJ이름', '닉네임');
INSERT INTO KILL_BET(LIVE, KILLGOAL, CREATED_DATE) VALUES (true, 90, NOW());
INSERT INTO TEAM(NAME, KILLBET_ID) VALUES ('A팀', 1);
INSERT INTO TEAM(NAME, KILLBET_ID) VALUES ('B팀', 1);
INSERT INTO MEMBER(TEAM_ID, NICKNAME) VALUES (1, '멤버1');
INSERT INTO MEMBER(TEAM_ID, NICKNAME) VALUES (1, '멤버22');
INSERT INTO MEMBER(TEAM_ID, NICKNAME) VALUES (2, '멤버3');
INSERT INTO MEMBER(TEAM_ID, NICKNAME) VALUES (2, '멤버44');