INSERT INTO BJ(NAME, NICKNAME) VALUES ('BJ이름', '닉네임');

INSERT INTO KILL_BET(LIVE, KILLGOAL, CREATED_DATE) VALUES (true, 90, NOW());
INSERT INTO KILL_BET(LIVE, KILLGOAL, CREATED_DATE) VALUES (false, 90, NOW());

INSERT INTO TEAM(NAME, KILLBET_ID) VALUES ('A팀', 1);
INSERT INTO TEAM(NAME, KILLBET_ID) VALUES ('B팀', 1);

INSERT INTO MEMBER(NICKNAME, BJ_ID, TEAM_ID) VALUES ('BJ이름', 1, 1);
INSERT INTO MEMBER(NICKNAME, TEAM_ID) VALUES ('BJ이름2', 2);
INSERT INTO MEMBER(NICKNAME, TEAM_ID) VALUES ('BJ이름2', 1);

INSERT INTO GAME(KILLBET_ID, MAP, CREATED_DATE) VALUES (1, '아렌델', NOW());